package:
  name: openktn
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
  - setuptools
  - numpy
  - networkx
  - pyunitwizard
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'This library...

    '
  dev_url: https://github.com/uibcdf/OpenKTN
  doc_url: https://uibcdf.org/OpenKTN
